import { ArrowRight, ShieldCheck, Truck, HeartHandshake, Stethoscope } from "lucide-react";
import Hero from "../components/Hero"; import SectionTitle from "../components/SectionTitle"; import Button from "../components/Button"; import CategoryCard from "../components/CategoryCard"; import ProductCard from "../components/ProductCard"; import ServiceCard from "../components/ServiceCard"; import VetCard from "../components/VetCard"; import TestimonialCard from "../components/TestimonialCard"; import BlogCard from "../components/BlogCard";
import {categories} from "../data/categories"; import {products} from "../data/products"; import {services} from "../data/services"; import {vets} from "../data/vets"; import {testimonials} from "../data/testimonials"; import {blogPosts} from "../data/blog";
export default function Home(){return <><Hero/><section className="section"><div className="container"><SectionTitle eyebrow="SHOP BY NEED" title="Everything for happier, healthier pets" description="Thoughtfully selected essentials for everyday care, play and wellbeing."/><div className="category-grid">{categories.map(c=><CategoryCard key={c.name} category={c}/>)}</div></div></section>
<section className="section soft"><div className="container"><div className="section-head"><SectionTitle eyebrow="FEATURED COLLECTION" title="Pet parents' favorites" description="Reliable essentials chosen for quality, comfort and everyday value." center={false}/><Button to="/shop" variant="outline">View All Products <ArrowRight size={17}/></Button></div><div className="product-grid">{products.slice(0,8).map(p=><ProductCard key={p.id} product={p}/>)}</div></div></section>
<section className="vet-promo"><div className="container vet-promo-grid"><div className="vet-promo-copy"><span className="eyebrow">PET SOLUTION VET & CARE</span><h2>Professional Care for Your Best Friend.</h2><p>From routine checkups and vaccinations to dental, skin and emergency care, our veterinary team puts your companion's wellbeing first.</p><div className="feature-list"><span><ShieldCheck/> Preventive-first care</span><span><HeartHandshake/> Compassionate approach</span><span><Stethoscope/> Experienced professionals</span></div><Button to="/appointment">Book an Appointment <ArrowRight size={17}/></Button></div><div className="vet-promo-image"><img src="https://images.unsplash.com/photo-1576201836106-db1758fd1c97?auto=format&fit=crop&w=1100&q=85" alt="Veterinarian caring for a dog"/></div></div></section>
<section className="section"><div className="container"><SectionTitle eyebrow="OUR SERVICES" title="More than a pet shop" description="A complete care ecosystem designed around the real needs of pets and their people."/><div className="service-grid">{services.map(s=><ServiceCard key={s.title} service={s}/>)}</div></div></section>
<section className="section soft"><div className="container"><SectionTitle eyebrow="WHY PET SOLUTION" title="Care you can count on" description="Professional standards, friendly support and products we would feel confident giving our own pets."/><div className="why-grid">{[["🛡️","Trusted Products","Carefully selected essentials from reliable brands."],["🩺","Professional Veterinary Care","Knowledgeable support for preventive and medical needs."],["👥","Experienced Team","People who genuinely understand pet parents."],["💰","Affordable Pricing","Great value without compromising on quality."],["🚚","Fast Delivery","Convenient delivery for everyday essentials."],["💬","Customer Support","Friendly help before and after your purchase."],["🐾","Pet-Friendly Environment","A welcoming place built around companion wellbeing."]].map(x=><div className="why-card" key={x[1]}><span>{x[0]}</span><h3>{x[1]}</h3><p>{x[2]}</p></div>)}</div></div></section>
<section className="section"><div className="container"><SectionTitle eyebrow="OUR VETS" title="Meet your pet's care team" description="Experienced professionals committed to thoughtful, transparent veterinary care."/><div className="vet-grid">{vets.map(v=><VetCard key={v.name} vet={v}/>)}</div></div></section>
<section className="section soft"><div className="container"><SectionTitle eyebrow="PET PARENTS SAY" title="Trusted by pet families" description="Realistic sample testimonials for this frontend demo."/><div className="testimonial-grid">{testimonials.map(t=><TestimonialCard key={t.name} item={t}/>)}</div></div></section>
<section className="section"><div className="container"><div className="section-head"><SectionTitle eyebrow="PET CARE TIPS" title="Practical advice for better pet care" description="Helpful reads for healthier routines and happier companions." center={false}/><Button to="/blog" variant="outline">View All Tips <ArrowRight size={17}/></Button></div><div className="blog-grid">{blogPosts.slice(0,3).map(p=><BlogCard key={p.id} post={p}/>)}</div></div></section>
<section className="newsletter"><div className="container newsletter-inner"><div><span className="eyebrow">STAY IN THE LOOP</span><h2>Better care starts with better information.</h2><p>Get useful pet-care tips and product updates.</p></div><form onSubmit={e=>{e.preventDefault(); alert("Thanks for subscribing! (Frontend demo)")}}><input required type="email" placeholder="Your email address"/><button className="btn btn-primary">Subscribe <ArrowRight size={17}/></button></form></div></section></>;}